Divide LND and CLN tests into separate runners
- LND and CLN setup and tests now run in their own individual jobs, which should improve the workflow speed.
- Introduced a new reusable action for handling test states.

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -1,7 +1,13 @@
 name: integration tests
 on: [push]
+env:
+  BITCOIN_VERSION: '22.0'
+  LSP_REF: 'breez-node-v0.16.2-beta'
+  CLIENT_REF: 'v0.16.2-breez'
+  GO_VERSION: '^1.19'
+  CLN_VERSION: 'v23.05.1'
 jobs:
-  setup:
+  setup-bitcoin-core:
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
@@ -11,26 +17,49 @@ jobs:
         if: steps.cache-bitcoin.outputs.cache-hit != 'true'
         uses: ./.github/actions/setup-bitcoin
         with:
-          bitcoin-version: '22.0'
+          bitcoin-version: ${{ env.BITCOIN_VERSION }}
+  setup-lnd-lsp:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
 
       - name: Set up LND LSP
         if: steps.cache-lnd-lsp.outputs.cache-hit != 'true'
         uses: ./.github/actions/setup-lnd-lsp
         with:
-          lsp-ref: 'breez-node-v0.16.2-beta'
-          go-version: ^1.19
+          lsp-ref: ${{ env.LSP_REF }}
+          go-version: ${{ env.GO_VERSION }}
+
+  setup-lnd-client:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
 
       - name: Set up LND client
         if: steps.cache-lnd-client.outputs.cache-hit != 'true'
         uses: ./.github/actions/setup-lnd-client
         with:
-          client-ref: 'v0.16.2-breez'
-          go-version: ^1.19
+          client-ref: ${{ env.CLIENT_REF }}
+          go-version: ${{ env.GO_VERSION }}
+
+  setup-cln:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
 
       - name: Set up Core Lightning
         uses: ./.github/actions/setup-clightning
         with:
-          checkout-version: 'v23.05.1'
+          checkout-version: ${{ env.CLN_VERSION }}
+
+  build-lspd:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
 
       - name: Build LSPD
         run: |
@@ -40,16 +69,120 @@ jobs:
           go build -o lspd_plugin ./cln_plugin/cmd
         shell: bash
 
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: build-artifacts
+          path: |
+            ./lspd
+            ./lspd_plugin
+
+  test-lsp-lnd:
+    runs-on: ubuntu-20.04
+    needs:
+      - setup-bitcoin-core
+      - setup-lnd-client
+      - setup-lnd-lsp
+      - setup-cln
+      - build-lspd
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: build-artifacts
+
+      - name: Set permissions
+        run: |
+          chmod 755 lspd
+          chmod 755 lspd_plugin
+        shell: bash
+
+      - name: Cache LND client
+        id: cache-lnd-client
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/go_lnd_client/bin/lnd
+          key: go_lnd_client-${{ env.CLIENT_REF }}-${{ env.GO_VERSION }}
+
+      - name: Cache Core Lightning
+        id: cache-core-lightning
+        uses: actions/cache@v2
+        with:
+          path: |
+            lightning_git/lightningd/lightning_hsmd
+            lightning_git/lightningd/lightning_gossipd
+            lightning_git/lightningd/lightning_openingd
+            lightning_git/lightningd/lightning_dualopend
+            lightning_git/lightningd/lightning_channeld
+            lightning_git/lightningd/lightning_closingd
+            lightning_git/lightningd/lightning_onchaind
+            lightning_git/lightningd/lightning_connectd
+            lightning_git/lightningd/lightning_websocketd
+            lightning_git/lightningd/lightningd
+            lightning_git/plugins/offers
+            lightning_git/plugins/topology
+            lightning_git/plugins/spenderp
+            lightning_git/plugins/test/run-route-overlong
+            lightning_git/plugins/test/run-funder_policy
+            lightning_git/plugins/pay
+            lightning_git/plugins/bkpr/test/run-bkpr_db
+            lightning_git/plugins/bkpr/test/run-recorder
+            lightning_git/plugins/funder
+            lightning_git/plugins/bookkeeper
+            lightning_git/plugins/txprepare
+            lightning_git/plugins/keysend
+            lightning_git/plugins/fetchinvoice
+            lightning_git/plugins/bcli
+            lightning_git/plugins/cln-grpc
+            lightning_git/plugins/commando
+            lightning_git/plugins/autoclean
+            lightning_git/plugins/chanbackup
+            lightning_git/plugins/sql
+            lightning_git/cli/lightning-cli
+            lightning_git/devtools/bolt11-cli
+            lightning_git/devtools/decodemsg
+            lightning_git/devtools/onion
+            lightning_git/devtools/dump-gossipstore
+            lightning_git/devtools/gossipwith
+            lightning_git/devtools/create-gossipstore
+            lightning_git/devtools/mkcommit
+            lightning_git/devtools/mkfunding
+            lightning_git/devtools/mkclose
+            lightning_git/devtools/mkgossip
+          key: core-lightning-${{ env.CLN_VERSION }}
+
+      - name: Cache Bitcoin Core
+        id: cache-bitcoin
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoind
+            ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoin-cli
+          key: bitcoin-core-${{ env.BITCOIN_VERSION }}
+
+      - name: Cache LND LSP
+        id: cache-lnd-lsp
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/go_lnd_lsp/bin/lnd
+          key: go_lnd_lsp-${{ env.LSP_REF }}-${{ env.GO_VERSION }}
+
       - name: Test LSPD
         run: |
           go get github.com/breez/lspd/itest
-          TESTRE="TestLspd"
+          # TESTRE="TestLspd/LND-lspd:"
+          TESTRE="TestLspd/LND-lspd:_testOpenZeroConfSingleHtlc"
           go test -timeout 45m -v \
             ./itest \
             -test.run \
             ${TESTRE} \
-            --bitcoindexec /usr/bin/bitcoind \
-            --bitcoincliexec /usr/bin/bitcoin-cli \
+            --bitcoindexec ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoind \
+            --bitcoincliexec ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoin-cli \
             --lightningdexec ${GITHUB_WORKSPACE}/lightning_git/lightningd/lightningd \
             --lndexec ~/go_lnd_lsp/bin/lnd \
             --lndmobileexec ~/go_lnd_client/bin/lnd \
@@ -60,30 +193,121 @@ jobs:
             --testdir /home/runner/test_state || echo "step_failed=true" >> $GITHUB_ENV
         shell: bash
 
-      - name: Check if test_state directory exists
-        id: check-test-state
-        run: |
-          ls -l
-          ls -l /home/runner/test_state
-          if [ -d "/home/runner/test_state" ]; then
-            echo "exists=true" >> $GITHUB_ENV
-          else
-            echo "exists=false" >> $GITHUB_ENV
-          fi
-        shell: bash
-
-      - name: Tar state
-        run: |
-          find /home/runner/test_state -type f -o -type d | tar -czf /home/runner/test_state.tar.gz -T -
-        shell: bash
-        if: env.exists == 'true'
-
-      - name: Upload test_state as artifact
-        uses: actions/upload-artifact@v2
+      - name: Process test state
+        uses: ./.github/actions/process-test-state
         with:
-          name: test_state_artifact
-          path: /home/runner/test_state.tar.gz
-        if: env.exists == 'true'
+          artifact-name: LND_state_artifact
+          test-state-path: /home/runner/test_state
+
+      - name: Fail the workflow if the tests failed
+        run: |
+          if [[ "${{ env.step_failed }}" == "true" ]]
+          then
+            exit 1
+          fi
+
+
+  test-lsp-cln:
+    runs-on: ubuntu-20.04
+    needs:
+      - setup-bitcoin-core
+      - setup-cln
+      - build-lspd
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Cache Core Lightning
+        id: cache-core-lightning
+        uses: actions/cache@v2
+        with:
+          path: |
+            lightning_git/lightningd/lightning_hsmd
+            lightning_git/lightningd/lightning_gossipd
+            lightning_git/lightningd/lightning_openingd
+            lightning_git/lightningd/lightning_dualopend
+            lightning_git/lightningd/lightning_channeld
+            lightning_git/lightningd/lightning_closingd
+            lightning_git/lightningd/lightning_onchaind
+            lightning_git/lightningd/lightning_connectd
+            lightning_git/lightningd/lightning_websocketd
+            lightning_git/lightningd/lightningd
+            lightning_git/plugins/offers
+            lightning_git/plugins/topology
+            lightning_git/plugins/spenderp
+            lightning_git/plugins/test/run-route-overlong
+            lightning_git/plugins/test/run-funder_policy
+            lightning_git/plugins/pay
+            lightning_git/plugins/bkpr/test/run-bkpr_db
+            lightning_git/plugins/bkpr/test/run-recorder
+            lightning_git/plugins/funder
+            lightning_git/plugins/bookkeeper
+            lightning_git/plugins/txprepare
+            lightning_git/plugins/keysend
+            lightning_git/plugins/fetchinvoice
+            lightning_git/plugins/bcli
+            lightning_git/plugins/cln-grpc
+            lightning_git/plugins/commando
+            lightning_git/plugins/autoclean
+            lightning_git/plugins/chanbackup
+            lightning_git/plugins/sql
+            lightning_git/cli/lightning-cli
+            lightning_git/devtools/bolt11-cli
+            lightning_git/devtools/decodemsg
+            lightning_git/devtools/onion
+            lightning_git/devtools/dump-gossipstore
+            lightning_git/devtools/gossipwith
+            lightning_git/devtools/create-gossipstore
+            lightning_git/devtools/mkcommit
+            lightning_git/devtools/mkfunding
+            lightning_git/devtools/mkclose
+            lightning_git/devtools/mkgossip
+          key: core-lightning-${{ env.CLN_VERSION }}
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: build-artifacts
+
+      - name: Set permissions
+        run: |
+          chmod 755 lspd
+          chmod 755 lspd_plugin
+        shell: bash
+
+      - name: Cache Bitcoin Core
+        id: cache-bitcoin
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoind
+            ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoin-cli
+          key: bitcoin-core-${{ env.BITCOIN_VERSION }}
+
+      - name: Test LSPD
+        run: |
+          go get github.com/breez/lspd/itest
+          TESTRE="TestLspd/CLN-lspd:_testOpenZeroConfSingleHtlc"
+          # TESTRE="TestLspd/CLN-lspd:"
+          go test -timeout 45m -v \
+            ./itest \
+            -test.run \
+            ${TESTRE} \
+            --bitcoindexec ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoind \
+            --bitcoincliexec ~/bitcoin-core-${{ env.BITCOIN_VERSION }}/bitcoin-${{ env.BITCOIN_VERSION }}/bin/bitcoin-cli \
+            --lightningdexec ${GITHUB_WORKSPACE}/lightning_git/lightningd/lightningd \
+            --clnpluginexec ${GITHUB_WORKSPACE}/lspd_plugin \
+            --lspdexec ${GITHUB_WORKSPACE}/lspd \
+            --lspdmigrationsdir ${GITHUB_WORKSPACE}/postgresql/migrations \
+            --preservelogs \
+            --testdir /home/runner/test_state || echo "step_failed=true" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Process test state
+        uses: ./.github/actions/process-test-state
+        with:
+          artifact-name: CLN_state_artifact
+          test-state-path: /home/runner/test_state
 
       - name: Fail the workflow if the tests failed
         run: |
